

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      # Docker PostgreSQL environment variables
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: hackathon_db


    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"


volumes:
  db_data:
  